"""add test_type retry_count test_cases report_path to test_runs

Revision ID: d5a994186ec7
Revises: 5e9d946a7c04
Create Date: 2026-04-12 22:11:18.804197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a994186ec7'
down_revision: Union[str, Sequence[str], None] = '5e9d946a7c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE testtype AS ENUM ('UNIT', 'INTEGRATION', 'E2E')")
    op.add_column('test_runs', sa.Column('test_type', sa.Enum('UNIT', 'INTEGRATION', 'E2E', name='testtype'), nullable=False))
    op.add_column('test_runs', sa.Column('test_cases', sa.Text(), nullable=True))
    op.add_column('test_runs', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('test_runs', sa.Column('report_path', sa.String(length=512), nullable=True))
    op.alter_column('test_runs', 'test_command',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_runs', 'test_command',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('test_runs', 'report_path')
    op.drop_column('test_runs', 'retry_count')
    op.drop_column('test_runs', 'test_cases')
    op.drop_column('test_runs', 'test_type')
    op.execute("DROP TYPE testtype")
    # ### end Alembic commands ###
